---
title: "newrmd"
author: "Danty_Zhang"
date: "2020/10/30"
output: html_document
---
```{r }
library(tidyr)
library(sqldf)
library(openxlsx)
options(stringsAsFactors = F)
```

```{r thyUS甲状腺超声数据分为SLE组和非SLE组}
rm(list = ls())
##bigmerge3--甲状腺超声数据---------------------------------
##超声结果##需要加SLE病人分组 diag_SLEnonSLE
thyroid_US<-read.csv(file="../7.supdat_US/16.US_SLE_nonSLE_deletdup.csv",header=TRUE)##甲状腺超声
thyroid_USnode<-read.csv(file="../7.supdat_US/16.US_all_node1.0_deletdup.csv",header=TRUE)##甲状腺超声
load(file="../2.diagdat/diag4_SLEnonSLE.Rdata")
load(file="../4.uniqueID/uniqueid.rdata")
load(file="../../数据库-风湿科住院病人数据/allpdatsex.rdata")

dim(thyroid_US);colnames(thyroid_US)
dim(thyroid_USnode);colnames(thyroid_USnode)

thyUS<-merge(thyroid_US[,-c(2,7,8)],diag_SLEnonSLE,by="BLH",all.x=T)  ##1133
thyUSnode<-merge(thyroid_USnode[,-c(2,11,12)],diag_SLEnonSLE,by="BLH",all.x=T)  #788
```

```{r 超声数据个体去重复}
thyUS<-merge(thyUS,uniqueid[,c(1,2,3,4,5)],by="BLH",all.x=T)
#
thyUS<-sqldf("SELECT * FROM thyUS GROUP BY GivenName,uniqueID ORDER BY BLH,入院日期")#979
thyUS<-thyUS[!is.na(thyUS$uniqueID),] #978
```

```{r 超声node数据个体去重复}
thyUSnode<-merge(thyUSnode,uniqueid[,c(1,2,3,4,5)],by="BLH",all.x=T)
#
thyUSnode<-sqldf("SELECT * FROM thyUSnode GROUP BY GivenName,uniqueID ORDER BY BLH,入院日期")#979
thyUSnode<-thyUSnode[!is.na(thyUSnode$uniqueID),] #685
```

```{r thyUS DATAPRE}
data<-thyUS
names(data)
dput(names(data))
factorVars<-c("有无结节", "分级", "简", "大小", "SLE")
data[factorVars]<-lapply(data[factorVars],factor)
str(data)
library(naniar)
vis_miss(data)
```

```{r thyUS all}
citation("tableone")  
library(tableone)
VARS<-c("有无结节", "分级", "简", "大小","年龄",  "SLE")
table1 <- CreateTableOne(vars = VARS,# strata = 'response', 
                         factorVars = factorVars,
                         data = data)
table1 <- print(table1, missing=TRUE,
                smd = TRUE,showAllLevels = TRUE)##,exact=c("esrd","die","acl")

table1 <- print(table1, smd = TRUE)
write.csv(table1, file = "14.thyUS_all.csv")

```

```{r thyUS_SLE}
table1 <- CreateTableOne(vars = VARS, strata = 'SLE', 
                         factorVars = factorVars,
                         data = data)
table1 <- print(table1, missing=TRUE,
                smd = TRUE,showAllLevels = TRUE)##,exact=c("esrd","die","acl")

table1 <- print(table1, smd = TRUE)
write.csv(table1, file = "14.thyUS_SLE.csv")
```


```{r thyroid_USnode DATAPRE}
data<-thyUSnode
names(data)
dput(names(data))
factorVars<-c("有无结节", "简", "腺体大小", "结节分级","左右叶", "个数", "SLE")
data[factorVars]<-lapply(data[factorVars],factor)
str(data)
library(naniar)
vis_miss(data)
data$`结节大小_1`<-as.numeric(data$`结节大小_1`)
data$`结节大小_2`<-as.numeric(data$`结节大小_2`)
```


```{r thyroid_USnode all}
data<-thyUSnode
citation("tableone")  
library(tableone)
VARS<-c("有无结节", "简", "腺体大小", "结节分级", "结节大小_1", 
"结节大小_2", "左右叶", "个数", "SLE")
table1 <- CreateTableOne(vars = VARS,# strata = 'response', 
                         factorVars = factorVars,
                         data = data)
table1 <- print(table1, missing=TRUE,
                smd = TRUE,showAllLevels = TRUE)##,exact=c("esrd","die","acl")

table1 <- print(table1, smd = TRUE)
write.csv(table1, file = "14.thyUSnode_all.csv")
```


```{r thyroid_USnode_SLE}
VARS<-c("有无结节", "简", "腺体大小", "结节分级","左右叶", "年龄", "结节大小_1", 
"结节大小_2",  "个数", "SLE")
table1 <- CreateTableOne(vars = VARS, strata = 'SLE', 
                         factorVars = factorVars,
                         data = data)
table1 <- print(table1, missing=TRUE,
                smd = TRUE,showAllLevels = TRUE)##,exact=c("esrd","die","acl")

table1 <- print(table1, smd = TRUE)
write.xlsx(table1,file="14.thyUSnode_SLE.xlsx",sep = "/t",)
write.csv(table1, file = "14.thyUSnode_SLE.csv")
?write.xlsx
```

