---
title: "newrmd"
author: "Danty_Zhang"
date: "2020/10/30"
output: html_document
---
```{r packages}
rm(list = ls())
library(tidyr)
library(sqldf)
library(openxlsx)
options(stringsAsFactors = F)
library(stringr)
options(scipen=200)
# library(tidyverse)
library(dplyr)
library(readxl)
library(sqldf)
library(tableone)
library("magrittr")
library("tidyr")
library("rlang")
```

```{r SLE labdat} 
##screen for those with thyroid funtion test
load(file="../6.labdat/final_labdat_SP_2w.Rdata")

#select the lab test needed
labitem<-read.xlsx("实验室检查_need.xlsx",sheet =1,rowNames = F)
labitem<-labitem[labitem$need==1,]
labitem<-na.omit(labitem)
labitem<-labitem$BLH
labitem<-c("BLH",labitem)
nlabdat<-labdat_SP_2w[,labitem]
```

```{r SLE pdat}
#retrieve uniqueID and remove duplicate, for the same patient only the first inpatient record were selected
load(file="../1.rawdata/pdat.rdata")
merge1<-merge(pdat,nlabdat,by = "BLH",all.x = T)
colnames(merge1)[4]<-"age"
first_visit<-sqldf("SELECT * FROM merge1 GROUP BY GivenName ORDER BY BLH ASC")
firstvisittime<-first_visit[,c(1,2,7)]
colnames(firstvisittime)[3]<-"time_firstvisit"
firstvisittime$`第一次住院访视`<-"1"
aa<-firstvisittime[,c(2,3)] #name_firt_visittime
merge1<-merge(merge1,aa,by="GivenName",all.x = T)
bb<-firstvisittime[,c(1,4)]
merge1<-merge(merge1,bb,by="BLH",all.x = T)
```


```{r SLE pdat}
###计算距离第一次入院时间
merge1$time_firstvisit<-strptime(merge1$time_firstvisit,format="%Y-%m-%d %H:%M:%S")
merge1$InHospitalDate<-strptime(merge1$InHospitalDate,format="%Y-%m-%d %H:%M:%S")
mergetest<-merge1[,c(1,2,7,8,585)]
merge1$`距初次住院时间`<-merge1$InHospitalDate-merge1$time_firstvisit
merge1$`距初次住院时间`<-str_replace_all(merge1$`距初次住院时间`,"hours","")
merge1$`距初次住院时间`<-as.numeric(merge1$`距初次住院时间`)
merge1$`距初次住院时间`<-round(merge1$`距初次住院时间`/(365*24),2)
merge1$`初次住院年份`<-lubridate::year(merge1$time_firstvisit)

merge1$`初次住院年份`<-as.character(merge1$`初次住院年份`)
merge1$InHospitalDate<-as.character(merge1$InHospitalDate)
merge1$time_firstvisit<-as.character(merge1$time_firstvisit)

BLH1y<-merge1[merge1$`距初次住院时间`>1,]$GivenName;BLH1y<-unique(BLH1y) #592
BLH2y<-merge1[merge1$`距初次住院时间`>2,]$GivenName;BLH2y<-unique(BLH2y)  #406
BLH3y<-merge1[merge1$`距初次住院时间`>3,]$GivenName;BLH3y<-unique(BLH3y) #270
BLH4y<-merge1[merge1$`距初次住院时间`>4,]$GivenName;BLH4y<-unique(BLH4y) #163
BLH5y<-merge1[merge1$`距初次住院时间`>5,]$GivenName;BLH5y<-unique(BLH5y) #91
merge1$`随访大于1年`<-ifelse(merge1$GivenName %in% BLH1y,"1","0")
merge1$`随访大于2年`<-ifelse(merge1$GivenName %in% BLH2y,"1","0")
merge1$`随访大于3年`<-ifelse(merge1$GivenName %in% BLH3y,"1","0")
merge1$`随访大于4年`<-ifelse(merge1$GivenName %in% BLH4y,"1","0")
merge1$`随访大于5年`<-ifelse(merge1$GivenName %in% BLH5y,"1","0")

man<-read.xlsx("merge_手工录入2021.7.3.xlsx")
man<-man[,c(2,4)]

merge1<-merge(merge1,man,by="BLH",all.x = T)

merge1<-sqldf("SELECT * FROM merge1 ORDER BY GivenName,BLH")
merge1$BLHorder<-1:6658
merge1<-merge1[,c(1:4,585:595,5:584)]


#diag
load(file="../2.diagdat/ALL_diagmerge.Rdata")
a<-unique(colnames(diag_merge_all))
diag<-a[grepl("_merge",a)]
diag_merge_part<-diag_merge_all[,c("BLH",diag)]
# load(file="../2.diagdat/diag2_all_fill1.Rdata")
merge1<-merge(merge1,diag_merge_part,by="BLH",all.x =T)

write.xlsx(merge1,file="inception_cohort.xlsx") ##backup of rawdata
```
